In [93]:
import pandas as pd

In [94]:
df = pd.read_csv("marathon-data.csv")
df.head()

   age gender     split     final
0   33      M  01:05:38  02:08:51
1   32      M  01:06:26  02:09:28
2   31      M  01:06:49  02:10:42
3   38      M  01:06:16  02:13:45
4   31      M  01:06:32  02:13:59

In [95]:
df['final'] = pd.to_timedelta(df.final).dt.total_seconds() / 60.0
df.head()

   age gender     split       final
0   33      M  01:05:38  128.850000
1   32      M  01:06:26  129.466667
2   31      M  01:06:49  130.700000
3   38      M  01:06:16  133.750000
4   31      M  01:06:32  133.983333

In [96]:
band_edges = [0] + [i for i in range(180, 390, 30)] + [float('inf')]
band_labels = ['sub 3', '3-3:30', '3:30-4', '4-4:30', '4:30-5', '5-5:30', '5:30-6', '6+']

df["band"] = pd.cut(
    df.final,
    bins=band_edges,
    labels=band_labels,
    right=False
)
df.head()

   age gender     split       final   band
0   33      M  01:05:38  128.850000  sub 3
1   32      M  01:06:26  129.466667  sub 3
2   31      M  01:06:49  130.700000  sub 3
3   38      M  01:06:16  133.750000  sub 3
4   31      M  01:06:32  133.983333  sub 3

In [97]:
df.band.value_counts(normalize=True)

band
4:30-5    0.181638
4-4:30    0.171114
5-5:30    0.169826
3:30-4    0.130980
6+        0.126819
5:30-6    0.112161
3-3:30    0.081557
sub 3     0.025906
Name: proportion, dtype: float64