In [1]:
import pandas as pd

In [8]:
# price list histroy with pizz_id, effective_date, price
price_hist_df = pd.read_csv("price_history.csv", parse_dates=["effective_date"])
price_hist_df.head()

   pizza_id effective_date  price
0         1     2026-01-01  20.75
1         2     2026-01-01  17.95
2         3     2026-01-01  20.75
3         4     2026-01-01  16.50
4         5     2026-01-01  20.25

In [11]:
# Get Products with pizza_id, name, current_price
products_df = pd.read_csv("products.csv")
products_df.head()

   pizza_id             name  current_price
0         1      BBQ Chicken          20.75
1         2           Cheese          18.50
2         3  Chicken Alfredo          20.75
3         4         Hawaiian          20.50
4         5       Margherita          20.75

In [14]:
# Transactions that have happened with order_detail_id. order_id, order_date, pizza_id, quantity
transactions_df = pd.read_csv("transactions.csv", parse_dates=["order_date"])
transactions_df.head()

   order_detail_id  order_id order_date  pizza_id  quantity
0                1         1 2026-01-01         4         1
1                2         2 2026-01-01         6         1
2                3         2 2026-01-01         2         1
3                4         2 2026-01-01         9         1
4                5         2 2026-01-01        10         1

In [24]:
# merge transactions with the price_history
transactions_price_hist_df = pd.merge_asof(transactions_df,
    price_hist_df,
    left_on="order_date",
    right_on="effective_date",
    by="pizza_id",
    direction="backward"
)
transactions_price_hist_df.head()

,order_detail_id,order_id,order_date,pizza_id,quantity,effective_date,price
0,1,1,2026-01-01,4,1,2026-01-01,16.50
1,2,2,2026-01-01,6,1,2026-01-01,17.50
2,3,2,2026-01-01,2,1,2026-01-01,17.95
3,4,2,2026-01-01,9,1,2026-01-01,20.75
4,5,2,2026-01-01,10,1,2026-01-01,20.25

In [26]:
# get the sum of the transactions and round to get the flag
total = transactions_price_hist_df['price'] * transactions_price_hist_df['quantity']
total.sum()

161144.34999999998