In [7]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv("manhattan_property_sales.csv")
df.head()

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,14999999
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,13500000
2,CHELSEA,204 WEST 21ST STREET,10011,A4,3365,7650000
3,CHELSEA,481 WEST 22 STREET,10011,A4,3666,0
4,CHELSEA,344 W 22 STREET,10011,A4,4395,13100000

In [12]:
df['PRICE_PER_SQ_FOOT'] = df['SALE_PRICE'].replace(0, np.NaN) / df['SQUARE_FEET']
df.head()

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE,PRICE_PER_SQ_FOOT
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,14999999,1667.222296
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,13500000,4437.869822
2,CHELSEA,204 WEST 21ST STREET,10011,A4,3365,7650000,2273.402675
3,CHELSEA,481 WEST 22 STREET,10011,A4,3666,0,NaN
4,CHELSEA,344 W 22 STREET,10011,A4,4395,13100000,2980.659841

In [17]:
df['AVG_PRICE_PER_SQ_FOOT'] = df.groupby(['ZIP_CODE', 'BUILDING_CLASS'])['PRICE_PER_SQ_FOOT'].transform('mean')
df.head()

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE,PRICE_PER_SQ_FOOT,AVG_PRICE_PER_SQ_FOOT
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,14999999,1667.222296,2668.274136
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,13500000,4437.869822,2668.274136
2,CHELSEA,204 WEST 21ST STREET,10011,A4,3365,7650000,2273.402675,2668.274136
3,CHELSEA,481 WEST 22 STREET,10011,A4,3666,0,NaN,2668.274136
4,CHELSEA,344 W 22 STREET,10011,A4,4395,13100000,2980.659841,2668.274136

In [32]:
df['MARKET_VALUE'] = np.where(df.SALE_PRICE > 0, df.SALE_PRICE, df.AVG_PRICE_PER_SQ_FOOT * df.SQUARE_FEET)
df.head()

,NEIGHBORHOOD,ADDRESS,ZIP_CODE,BUILDING_CLASS,SQUARE_FEET,SALE_PRICE,PRICE_PER_SQ_FOOT,AVG_PRICE_PER_SQ_FOOT,MARKET_VALUE
0,CHELSEA,150 WEST 15TH STREET,10011,A4,8997,14999999,1667.222296,2668.274136,1.500000e+07
1,CHELSEA,348 WEST 22 STREET,10011,A4,3042,13500000,4437.869822,2668.274136,1.350000e+07
2,CHELSEA,204 WEST 21ST STREET,10011,A4,3365,7650000,2273.402675,2668.274136,7.650000e+06
3,CHELSEA,481 WEST 22 STREET,10011,A4,3666,0,NaN,2668.274136,9.781893e+06
4,CHELSEA,344 W 22 STREET,10011,A4,4395,13100000,2980.659841,2668.274136,1.310000e+07

In [34]:
# Flag over 15 million in market value
len(df[df['MARKET_VALUE'] > 15_000_000])

19